default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: amplify_development

test:
  <<: *default
  database: amplify_test

production:
  <<: *default
  database: amplify_production

staging:
  <<: *default
  database: amplify_staging
